version: '3.1'
services:
  backendweb:
    container_name: spring-demo 
    restart: always
    build: ./
    ports:
      - "8080:8080"
    environment: 
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employee_directory
      - spring.datasource.username=springstudent
      - spring.datasource.password=springstudent
    networks:
      - springmysql
    depends_on: 
    - mysqldb
  mysqldb:
    image: mysql
    restart: always
    container_name: mysqldb
    ports:
      - 3307:3306
    expose:
      - "3306"
    networks:
      - springmysql
    environment:
      - MYSQL_ROOT_PASSWORD=springstudent
      - MYSQL_DATABASE=employee_directory
      - MYSQL_USER=springstudent
      - MYSQL_PASSWORD=springstudent

networks:
  springmysql:
    name: springmysql
    driver: bridge