version: '3.8'
services:
  backend:
    container_name: spring-demo 
    image: spring-demo
    restart: always
    build: ./
    ports:
      - "8080:8080"
    environment: 
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employee_directory?autoReconnect=true
    networks:
      - springmysql
    depends_on: 
      mysqldb:
        condition: service_healthy
  mysqldb:
    image: mysql:8.0
    ports:
      - "3307:3306"
    expose:
      - "3306"
    networks:
      - springmysql
    environment:
      MYSQL_ROOT_PASSWORD: springstudent
      MYSQL_DATABASE: employee_directory
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
      MYSQL_ROOT_HOST: '%'  # Tüm hostlara root erişimi
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped
networks:
  springmysql:
    name: springmysql
    driver: bridge